#!/usr/bin/env bash
# this script configures your domain zone so that the subdomain www points to your load balancers IP

SUB_DOMAIN=("www" "lb-01" "web-01" "web-02")
domain_subdomain ()
{
	# ensure there are two arguments passed
	if [ "$#" -lt 1  ]
	then
		echo "usage: <$0> <arg1: domain> <arg2: subdomain>"
		echo "Both arguments type: string. Subdomain is optional"
		return 1
	fi

	domain=$1
	# if only domain is passed
	if [ "$#" -eq 1 ]
	then
		for sub in "${SUB_DOMAIN[@]}"
		do
			ip=$(dig "$sub.$domain" +short)
			typ=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
			echo "The subdomain $sub is a $typ record and points to $ip"
		done
	# if domain and subdomain are passed
	elif [ "$#" -eq 2 ]
	then
		ip=$(dig "$2.$domain" +short)
		typ=$(dig "$2.$domain" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
		echo "The subdomain $2 is a $typ record and points to $ip"
	fi
}

# call the function with provided arguments
domain_subdomain "$@"
