#!/usr/bin/env bash
# this script takes 4 parameters: source, server_ip, username, destination

if [ "$#" -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp "$1" "$3"@"$2":"$4"
fi
