#!/usr/bin/env bash
# this script takes 4 parameters: source, server_ip, username, destination

if [ "$#" -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":"~/"
fi
