#!/usr/bin/env bash
# this script configures nginx server so that /redirect_me
# redirects to another page

# update linux headers
apt-get install update

# install nginx server
apt-get install nginx -y

# start nginx
service nginx start

# add location /redirect_me after the server_name
sed -i 's/server_name _;/&\n location \/redirect_me {\n return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n }/' /etc/nginx/sites-available/default


service nginx reload
