#!/usr/bin/env bash
# this script configures nginx server so that /redirect_me
# redirects to another page

# update linux headers
apt-get install update

# install nginx server
apt-get install nginx -y

# start nginx
service nginx start

# change the permissions to allow read, write, execute for root
chmod -R 755 /var/www/

# create redirect file
touch /var/www/html/redirect_me

# Ensure nginx is listening on port 80
sed -i 's/server_name _;/&\n    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }/' /etc/nginx/sites-available/default

# Restart nginx to apply the new configuration
service nginx reload

