#!/usr/bin/env bash
# this script configures nginx server web-02 to be identical to web-01
# starts by installing nginx and configuring it

# update linux headers
apt-get install update

# install nginx server
apt-get install nginx -y

# start nginx
service nginx start

# add the landing page after changing permissions
chmod 755 -R /var/www/

# add the index page
echo "Hello World!" > /var/www/html/index.html

# make a copy of default nginx configurations
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# add location /redirect_me after the server_name
sed -i 's/server_name _;/&\n\t location \/redirect_me {\n return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n }/' /etc/nginx/sites-available/default

# add headers right after the server_name as well
sed -i "s/server_name _;/&\n\t add_header X-Served-By \$HOSTNAME;/" /etc/nginx/sites-available/default

# test nginx for syntax errors
nginx -t

service nginx reload
