#!/usr/bin/env bash
# this script changes defaulr port of nginx to 80.

# Ensure it is run by root
# alert user on privileges

if [[ $EUID -ne 0  ]]; then
	echo "Run as root"
	exit 1
fi

# Scan for the hosts ipv4 address: just list the ip
# ips=($(ip addr show | sed -nE '/inet /{s/.*inet ([0-9.]+).*/\1/; /127\.0\.0\.1/d; p}'))

# start nginx
service nginx start

#read is used in a while loop to read each line of the output of ip addr show | sed
while IFS= read -r ip; do
	ips+=("$ip")
done < <(ip addr show | sed -nE '/inet /{s/.*inet ([0-9.]+).*/\1/; /127\.0\.0\.1/d; p}')

# proceed to scan for all open ports in all ip addresses
n=0
for ip in "${ips[@]}"; do
	echo "Scan started for ip_$n: $ip"	
	# Cut out the active port that nginx is running on
	prt=$(nmap -A "$ip" | grep -E '^[0-9]+/tcp.*nginx' | cut -d '/' -f 1)
	echo "Nginx is running on: $prt"

	# change the nginx port to 80 for all the specific IPs
	sed -i "s/$prt/80/g" /etc/nginx/sites-available/default
	(( n++ ))
done

echo "restarting nginx"
service nginx reload
echo "nginx restarted"
