#!/usr/bin/env bash
# This script displays fizzbuzz when the number is a multiple of 3 and 5
# Fizz for multiples of 3, Buzz for multiples of 5 else number
i=1
while [ $i -le 100 ]
do
	if (($i % 3 == 0)) && (($i % 5 == 0))
	then
		echo "FizzBuzz"
	elif (($i % 3 == 0))
	then
		echo "Fizz"
	elif (($i % 5 == 0))
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
