#!/usr/bin/env bash
# This script displays "Best School" 10 times
# For the 9th Best School, also display "Hi"
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i == 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
