#!/usr/bin/env bash
# This script displays 1-20, bad luck messages
# 4 from china, 9 japan, 17 italy
i=1
while [ $i -le 20 ]
do
	echo "$i"
	if [ $i == 4 ]
	then
		echo "bad luck from China"
	elif [ $i == 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i == 17 ]
	then
		echo "bad luck from Italy"
	fi
	((i++))
done

