#!/usr/bin/env bash
# This script displays 1-20, bad luck messages
# 4 from china, 9 japan, 17 italy
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in 
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
	*)
		;;
	esac
	((i++))
done
