#!/usr/bin/env bash
# This script displays the content of current directory
# in a list format

for file in *; do
	if [[ ! "$file" == .* ]]
	then
		after_dash=$(echo "$file" | cut -d '-' -f 2-)
		echo "$after_dash"
	fi
done
