#!/usr/bin/env bash
# this script configures default nginx to run using user nginx and listen on port 8080

if ! command -v nginx &> /dev/null
then
	echo "installing nginx ... "
	apt-get update
	apt-get install nginx -y
fi

# stop nginx if it is running
service nginx stop

# change nginx user to nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# change the port nginx is listening on to 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# restart nginx
service nginx start
