#!/usr/bin/env bash
# config file to disable authentication through passwords
# ssh user@HostName <requires you have a RSA pair>

Host kZ
	HostName 54.174.207.67
	User ubuntu
	IdentityFile ~/.ssh/school
	PreferredAuthentications publickey
	PasswordAuthentication no
